// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Thermometar.proto

package iots_temperature_srv_Thermometar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomTemperatrue struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	Temperature          int64    `protobuf:"varint,2,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomTemperatrue) Reset()         { *m = RoomTemperatrue{} }
func (m *RoomTemperatrue) String() string { return proto.CompactTextString(m) }
func (*RoomTemperatrue) ProtoMessage()    {}
func (*RoomTemperatrue) Descriptor() ([]byte, []int) {
	return fileDescriptor_60ba8805a72066c2, []int{0}
}

func (m *RoomTemperatrue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomTemperatrue.Unmarshal(m, b)
}
func (m *RoomTemperatrue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomTemperatrue.Marshal(b, m, deterministic)
}
func (m *RoomTemperatrue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomTemperatrue.Merge(m, src)
}
func (m *RoomTemperatrue) XXX_Size() int {
	return xxx_messageInfo_RoomTemperatrue.Size(m)
}
func (m *RoomTemperatrue) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomTemperatrue.DiscardUnknown(m)
}

var xxx_messageInfo_RoomTemperatrue proto.InternalMessageInfo

func (m *RoomTemperatrue) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomTemperatrue) GetTemperature() int64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type Degrees struct {
	Temperature          int64    `protobuf:"varint,1,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Degrees) Reset()         { *m = Degrees{} }
func (m *Degrees) String() string { return proto.CompactTextString(m) }
func (*Degrees) ProtoMessage()    {}
func (*Degrees) Descriptor() ([]byte, []int) {
	return fileDescriptor_60ba8805a72066c2, []int{1}
}

func (m *Degrees) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Degrees.Unmarshal(m, b)
}
func (m *Degrees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Degrees.Marshal(b, m, deterministic)
}
func (m *Degrees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Degrees.Merge(m, src)
}
func (m *Degrees) XXX_Size() int {
	return xxx_messageInfo_Degrees.Size(m)
}
func (m *Degrees) XXX_DiscardUnknown() {
	xxx_messageInfo_Degrees.DiscardUnknown(m)
}

var xxx_messageInfo_Degrees proto.InternalMessageInfo

func (m *Degrees) GetTemperature() int64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_60ba8805a72066c2, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RoomTemperatrue)(nil), "iots.temperature.srv.Thermometar.RoomTemperatrue")
	proto.RegisterType((*Degrees)(nil), "iots.temperature.srv.Thermometar.Degrees")
	proto.RegisterType((*Empty)(nil), "iots.temperature.srv.Thermometar.Empty")
}

func init() {
	proto.RegisterFile("Thermometar.proto", fileDescriptor_60ba8805a72066c2)
}

var fileDescriptor_60ba8805a72066c2 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0xc9, 0x48, 0x2d,
	0xca, 0xcd, 0xcf, 0x4d, 0x2d, 0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xc8,
	0xcc, 0x2f, 0x29, 0xd6, 0x2b, 0x49, 0xcd, 0x2d, 0x48, 0x2d, 0x4a, 0x2c, 0x29, 0x2d, 0x4a, 0xd5,
	0x2b, 0x2e, 0x2a, 0xd3, 0x43, 0x52, 0xa7, 0xe4, 0xcf, 0xc5, 0x1f, 0x94, 0x9f, 0x9f, 0x1b, 0x02,
	0x55, 0x52, 0x54, 0x9a, 0x2a, 0x24, 0xc5, 0xc5, 0x01, 0x12, 0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x14, 0xb8, 0xb8, 0x43, 0x10, 0xa6, 0x49, 0x30,
	0x29, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x0b, 0x29, 0x69, 0x73, 0xb1, 0xbb, 0xa4, 0xa6, 0x17, 0xa5,
	0xa6, 0x16, 0xa3, 0x2b, 0x66, 0xc4, 0x54, 0xcc, 0xce, 0xc5, 0xea, 0x9a, 0x5b, 0x50, 0x52, 0x69,
	0x74, 0x8d, 0x89, 0x8b, 0x1b, 0xc9, 0x59, 0x42, 0x99, 0x5c, 0x9c, 0xee, 0xa9, 0x25, 0xc1, 0x25,
	0x89, 0x25, 0xa5, 0xc5, 0x42, 0xea, 0x7a, 0x84, 0xbc, 0xa1, 0x07, 0x36, 0x45, 0xca, 0x90, 0xb0,
	0x42, 0x34, 0xcf, 0x2a, 0x31, 0x08, 0xe5, 0x72, 0x71, 0x3b, 0xe7, 0xe7, 0xe7, 0x84, 0x64, 0xa4,
	0x82, 0xe4, 0x84, 0x34, 0x09, 0x9b, 0x01, 0xf5, 0x1f, 0xd9, 0xd6, 0x79, 0xa4, 0x26, 0x96, 0xd0,
	0xc9, 0xba, 0x24, 0x36, 0x70, 0x42, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x58, 0xe9, 0xde,
	0x00, 0x1d, 0x02, 0x00, 0x00,
}
