// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TemperatureControlSystem.proto

package iots_temperature_srv_TemperatureControlSystem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5869230258237f, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Room struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5869230258237f, []int{1}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RoomTemperatrue struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	Temperature          int64    `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomTemperatrue) Reset()         { *m = RoomTemperatrue{} }
func (m *RoomTemperatrue) String() string { return proto.CompactTextString(m) }
func (*RoomTemperatrue) ProtoMessage()    {}
func (*RoomTemperatrue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5869230258237f, []int{2}
}

func (m *RoomTemperatrue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomTemperatrue.Unmarshal(m, b)
}
func (m *RoomTemperatrue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomTemperatrue.Marshal(b, m, deterministic)
}
func (m *RoomTemperatrue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomTemperatrue.Merge(m, src)
}
func (m *RoomTemperatrue) XXX_Size() int {
	return xxx_messageInfo_RoomTemperatrue.Size(m)
}
func (m *RoomTemperatrue) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomTemperatrue.DiscardUnknown(m)
}

var xxx_messageInfo_RoomTemperatrue proto.InternalMessageInfo

func (m *RoomTemperatrue) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomTemperatrue) GetTemperature() int64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

type AirConditioner struct {
	Room                 string   `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AirConditioner) Reset()         { *m = AirConditioner{} }
func (m *AirConditioner) String() string { return proto.CompactTextString(m) }
func (*AirConditioner) ProtoMessage()    {}
func (*AirConditioner) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5869230258237f, []int{3}
}

func (m *AirConditioner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AirConditioner.Unmarshal(m, b)
}
func (m *AirConditioner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AirConditioner.Marshal(b, m, deterministic)
}
func (m *AirConditioner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AirConditioner.Merge(m, src)
}
func (m *AirConditioner) XXX_Size() int {
	return xxx_messageInfo_AirConditioner.Size(m)
}
func (m *AirConditioner) XXX_DiscardUnknown() {
	xxx_messageInfo_AirConditioner.DiscardUnknown(m)
}

var xxx_messageInfo_AirConditioner proto.InternalMessageInfo

func (m *AirConditioner) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5869230258237f, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "iots.temperature.srv.TemperatureControlSystem.Message")
	proto.RegisterType((*Room)(nil), "iots.temperature.srv.TemperatureControlSystem.Room")
	proto.RegisterType((*RoomTemperatrue)(nil), "iots.temperature.srv.TemperatureControlSystem.RoomTemperatrue")
	proto.RegisterType((*AirConditioner)(nil), "iots.temperature.srv.TemperatureControlSystem.AirConditioner")
	proto.RegisterType((*Empty)(nil), "iots.temperature.srv.TemperatureControlSystem.Empty")
}

func init() {
	proto.RegisterFile("TemperatureControlSystem.proto", fileDescriptor_0f5869230258237f)
}

var fileDescriptor_0f5869230258237f = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcf, 0x4a, 0xf3, 0x40,
	0x10, 0xef, 0x7e, 0x6d, 0xbf, 0xea, 0x88, 0x55, 0xd6, 0x83, 0x25, 0x82, 0x84, 0xc5, 0x43, 0x2f,
	0xee, 0xc1, 0x7a, 0x55, 0x90, 0x54, 0x3c, 0x59, 0x21, 0xd1, 0x07, 0xd8, 0xe2, 0x20, 0x81, 0x6c,
	0x36, 0xec, 0x4e, 0x95, 0x80, 0x77, 0x2f, 0x5e, 0x7c, 0x23, 0x1f, 0x4d, 0x36, 0x58, 0x1b, 0x85,
	0x1e, 0x12, 0xc1, 0xdb, 0x64, 0x66, 0x7e, 0x7f, 0xf2, 0x1b, 0x16, 0x0e, 0x6f, 0x51, 0x17, 0x68,
	0x15, 0x2d, 0x2c, 0x46, 0x26, 0x27, 0x6b, 0xb2, 0xa4, 0x74, 0x84, 0x5a, 0x16, 0xd6, 0x90, 0xe1,
	0xc7, 0xa9, 0x21, 0x27, 0x69, 0xb5, 0x24, 0x9d, 0x7d, 0x94, 0xeb, 0x40, 0xe2, 0x00, 0x06, 0xd7,
	0xe8, 0x9c, 0x7a, 0x40, 0xbe, 0x0b, 0x5d, 0xa7, 0xca, 0x11, 0x0b, 0xd9, 0x78, 0x33, 0xf6, 0xa5,
	0x08, 0xa0, 0x17, 0x1b, 0xa3, 0x39, 0x87, 0x5e, 0xae, 0x34, 0x7e, 0x8e, 0xaa, 0x5a, 0xdc, 0xc0,
	0x8e, 0x9f, 0x2d, 0x89, 0xed, 0x02, 0x79, 0x00, 0x1b, 0xbe, 0x35, 0x5b, 0xad, 0x7e, 0x7d, 0xf3,
	0x10, 0xb6, 0x6a, 0x9e, 0x46, 0xff, 0x42, 0x36, 0xee, 0xc6, 0xf5, 0x96, 0x38, 0x82, 0xe1, 0x45,
	0x6a, 0x23, 0x93, 0xdf, 0xa7, 0x94, 0x9a, 0x1c, 0xad, 0x97, 0xb5, 0xc6, 0xe8, 0xa5, 0xac, 0xaf,
	0xc5, 0x00, 0xfa, 0x97, 0xba, 0xa0, 0xf2, 0xe4, 0xbd, 0x0f, 0xa3, 0x75, 0x7f, 0xc5, 0x5f, 0x18,
	0x0c, 0xaf, 0x90, 0x6a, 0x73, 0x3e, 0x91, 0x8d, 0x82, 0x91, 0xde, 0x79, 0x70, 0xde, 0x02, 0x54,
	0x4b, 0x44, 0x74, 0xf8, 0x1b, 0x83, 0xfd, 0x04, 0x69, 0x8a, 0x2e, 0xb5, 0x6a, 0x9e, 0x61, 0xdd,
	0xd2, 0x2f, 0xd9, 0x83, 0xd3, 0x86, 0xf8, 0x2a, 0x38, 0xd1, 0xe1, 0xcf, 0xb0, 0x1d, 0x59, 0x54,
	0x84, 0x33, 0x7c, 0xaa, 0xee, 0xdb, 0x2a, 0x9b, 0xb6, 0xea, 0xaf, 0x0c, 0xf6, 0x12, 0xa4, 0xbb,
	0xe2, 0xc7, 0xb5, 0xcf, 0x1a, 0xf2, 0x7d, 0x87, 0xb7, 0xb6, 0x53, 0x02, 0x4c, 0x31, 0x43, 0xc2,
	0x3f, 0x4f, 0x62, 0xfe, 0xbf, 0x7a, 0xb1, 0x93, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x4b,
	0x34, 0x88, 0xd3, 0x03, 0x00, 0x00,
}
