// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: TemperatureControlSystem.proto

package iots_temperature_srv_TemperatureControlSystem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TemperatureControlSystem service

type TemperatureControlSystemService interface {
}

type temperatureControlSystemService struct {
	c    client.Client
	name string
}

func NewTemperatureControlSystemService(name string, c client.Client) TemperatureControlSystemService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "iots.temperature.srv.TemperatureControlSystem"
	}
	return &temperatureControlSystemService{
		c:    c,
		name: name,
	}
}

// Server API for TemperatureControlSystem service

type TemperatureControlSystemHandler interface {
}

func RegisterTemperatureControlSystemHandler(s server.Server, hdlr TemperatureControlSystemHandler, opts ...server.HandlerOption) error {
	type temperatureControlSystem interface {
	}
	type TemperatureControlSystem struct {
		temperatureControlSystem
	}
	h := &temperatureControlSystemHandler{hdlr}
	return s.Handle(s.NewHandler(&TemperatureControlSystem{h}, opts...))
}

type temperatureControlSystemHandler struct {
	TemperatureControlSystemHandler
}
