// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TemperatureControlSystem.proto

package iots_temperature_srv_TemperatureControlSystem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5869230258237f, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "iots.temperature.srv.TemperatureControlSystem.Message")
}

func init() {
	proto.RegisterFile("TemperatureControlSystem.proto", fileDescriptor_0f5869230258237f)
}

var fileDescriptor_0f5869230258237f = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0b, 0x49, 0xcd, 0x2d,
	0x48, 0x2d, 0x4a, 0x2c, 0x29, 0x2d, 0x4a, 0x75, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0x09, 0xae,
	0x2c, 0x2e, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xd2, 0xcd, 0xcc, 0x2f, 0x29,
	0xd6, 0x2b, 0x41, 0x28, 0xd2, 0x2b, 0x2e, 0x2a, 0xd3, 0xc3, 0xa5, 0x49, 0x49, 0x9a, 0x8b, 0xdd,
	0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x48, 0x80, 0x8b, 0xb9, 0x38, 0xb1, 0x52, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x34, 0x92, 0xe2, 0x92, 0xc0, 0xa5, 0x31, 0x89, 0x0d, 0x6c,
	0x9d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x27, 0xb2, 0x61, 0x19, 0x90, 0x00, 0x00, 0x00,
}
